name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.expo.outputs.published_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Publish Expo Update
        id: expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          # publish and capture the JSON output
          PUBLISHED_URL=$(npx expo publish --non-interactive --json | jq -r .url)
          echo "::set-output name=published_url::$PUBLISHED_URL"
